web:
  image: index.alauda.cn/jamlee/docker-laravel-cn:latest
  ports:
    - "80:80"
  links:
    - db
    - redis
  extends:
    file: common.yml
    service: common
  command: "/bin/sh -c 'while true; do sleep 1; done'"
db:
  image: "mysql:5.6"
  ports:
    - "3306:3306"
  volumes:
    - ./config/mysql:/etc/mysql/conf.d
  volumes_from:
    - "dockerlaravelcn_data_1"
  environment:
    - "MYSQL_ROOT_PASSWORD=jamlee"
    - "MYSQL_DATABASE=laravel"

redis:
  image: "redis"
  ports:
    - "6379:6379"
  
